spring:
  application:
    name: life-os-api
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:55432/lifeos_local}
    username: ${DATABASE_USERNAME:lifeos_local_app}
    password: ${DATABASE_PASSWORD:lifeos_local_app_only}
    hikari:
      pool-name: LifeOsPool
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  mail:
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:1025}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /life-os/api/v1
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
