package tech.buildwithpartha.lifeos.export.domain;

/** Status lifecycle of a private generated export file. */
public enum ExportFileStatus {
  /** File archive is actively being generated by a worker job. */
  GENERATING,

  /** File archive has been written to private storage and is available for download. */
  READY,

  /** File retention period (7 days) has expired and storage was purged. */
  EXPIRED,

  /** Explicitly deleted by user request or account cleanup. */
  DELETED
}
