import type { TaskRecord } from "./task";
import type { TaskProjectOption } from "./taskScreen";

export interface MockTaskLabelOption {
  readonly id: string;
  readonly name: string;
}

export const MOCK_TASK_PROJECTS: readonly TaskProjectOption[] = [
  { id: "project-life-os", name: "LifeOS" },
  { id: "project-home", name: "Home admin" },
  { id: "project-learning", name: "Learning" },
];

export const MOCK_TASK_LABELS: readonly MockTaskLabelOption[] = [
  { id: "label-planning", name: "Planning" },
  { id: "label-deep-work", name: "Deep work" },
];

function project(id: string): TaskRecord["project"] {
  const match = MOCK_TASK_PROJECTS.find((option) => option.id === id);
  if (!match) return null;
  return { id: match.id, name: match.name, href: `/life-os/app/projects/${match.id}` };
}

export const MOCK_TASKS: readonly TaskRecord[] = [
  {
    id: "task-weekly-review",
    title: "Prepare weekly review",
    description: "Gather open Tasks and decide what moves forward.",
    status: "IN_PROGRESS",
    priority: "P1",
    project: project("project-life-os"),
    dueAt: "2026-08-22T12:00:00Z",
    estimateMinutes: 90,
    progress: 40,
    mitDate: "2026-08-21",
    isMit: true,
    commentCount: 3,
    blockerCount: 0,
    overdue: false,
    archivedAt: null,
    labelIds: ["label-planning"],
    version: 3,
    createdAt: "2026-08-18T09:00:00Z",
    updatedAt: "2026-08-21T08:00:00Z",
  },
  {
    id: "task-privacy-notice",
    title: "Draft privacy notice",
    description: "Write the public privacy notice from the accepted lifecycle.",
    status: "TO_DO",
    priority: "P2",
    project: project("project-life-os"),
    dueAt: "2026-08-19T17:00:00Z",
    estimateMinutes: 120,
    progress: 0,
    mitDate: null,
    isMit: false,
    commentCount: 1,
    blockerCount: 0,
    overdue: true,
    archivedAt: null,
    labelIds: [],
    version: 1,
    createdAt: "2026-08-10T11:00:00Z",
    updatedAt: "2026-08-19T09:00:00Z",
  },
  {
    id: "task-launch-checklist",
    title: "Finish launch checklist",
    description: "Waiting on the identity gate before this can move.",
    status: "BLOCKED",
    priority: "P1",
    project: project("project-life-os"),
    dueAt: "2026-08-25T10:00:00Z",
    estimateMinutes: 60,
    progress: 20,
    mitDate: null,
    isMit: false,
    commentCount: 4,
    blockerCount: 2,
    overdue: false,
    archivedAt: null,
    labelIds: ["label-planning"],
    version: 5,
    createdAt: "2026-08-12T14:00:00Z",
    updatedAt: "2026-08-20T16:00:00Z",
  },
  {
    id: "task-capacity-review",
    title: "Review next week capacity",
    description: null,
    status: "TO_DO",
    priority: "P3",
    project: project("project-life-os"),
    dueAt: "2026-08-24T09:00:00Z",
    estimateMinutes: 30,
    progress: 0,
    mitDate: null,
    isMit: false,
    commentCount: 0,
    blockerCount: 0,
    overdue: false,
    archivedAt: null,
    labelIds: [],
    version: 1,
    createdAt: "2026-08-20T07:00:00Z",
    updatedAt: "2026-08-20T07:00:00Z",
  },
  {
    id: "task-focus-session",
    title: "Schedule a focus session",
    description: "Protect two hours for deep writing.",
    status: "TO_DO",
    priority: "P2",
    project: project("project-learning"),
    dueAt: "2026-08-23T14:00:00Z",
    estimateMinutes: 120,
    progress: 0,
    mitDate: null,
    isMit: false,
    commentCount: 0,
    blockerCount: 0,
    overdue: false,
    archivedAt: null,
    labelIds: ["label-deep-work"],
    version: 1,
    createdAt: "2026-08-19T18:00:00Z",
    updatedAt: "2026-08-19T18:00:00Z",
  },
  {
    id: "task-home-bills",
    title: "Pay household bills",
    description: "Electricity and internet for this month.",
    status: "IN_PROGRESS",
    priority: "P3",
    project: project("project-home"),
    dueAt: "2026-08-21T18:00:00Z",
    estimateMinutes: 20,
    progress: 50,
    mitDate: null,
    isMit: false,
    commentCount: 0,
    blockerCount: 0,
    overdue: false,
    archivedAt: null,
    labelIds: [],
    version: 2,
    createdAt: "2026-08-15T08:00:00Z",
    updatedAt: "2026-08-21T06:00:00Z",
  },
  {
    id: "task-inbox-capture",
    title: "File open Brain Dump items",
    description: "Decide what each item becomes.",
    status: "TO_DO",
    priority: "P4",
    project: null,
    dueAt: null,
    estimateMinutes: null,
    progress: 0,
    mitDate: null,
    isMit: false,
    commentCount: 0,
    blockerCount: 0,
    overdue: false,
    archivedAt: null,
    labelIds: [],
    version: 1,
    createdAt: "2026-08-21T05:00:00Z",
    updatedAt: "2026-08-21T05:00:00Z",
  },
  {
    id: "task-retro-notes",
    title: "Write retrospective notes",
    description: "Capture what to keep and what to change.",
    status: "DONE",
    priority: "P3",
    project: project("project-life-os"),
    dueAt: "2026-08-18T16:00:00Z",
    estimateMinutes: 45,
    progress: 100,
    mitDate: null,
    isMit: false,
    commentCount: 2,
    blockerCount: 0,
    overdue: false,
    archivedAt: null,
    labelIds: [],
    version: 4,
    createdAt: "2026-08-11T10:00:00Z",
    updatedAt: "2026-08-18T16:30:00Z",
  },
  {
    id: "task-cancelled-spike",
    title: "Explore a second calendar provider",
    description: "Stopped after the v1 data posture was accepted.",
    status: "CANCELLED",
    priority: "P4",
    project: project("project-life-os"),
    dueAt: null,
    estimateMinutes: 180,
    progress: 10,
    mitDate: null,
    isMit: false,
    commentCount: 1,
    blockerCount: 0,
    overdue: false,
    archivedAt: null,
    labelIds: [],
    version: 2,
    createdAt: "2026-08-05T12:00:00Z",
    updatedAt: "2026-08-16T12:00:00Z",
  },
  {
    id: "task-archived-onboarding",
    title: "Rewrite onboarding copy draft",
    description: "Replaced by the accepted onboarding specification.",
    status: "TO_DO",
    priority: "P3",
    project: project("project-life-os"),
    dueAt: "2026-08-01T12:00:00Z",
    estimateMinutes: 60,
    progress: 15,
    mitDate: null,
    isMit: false,
    commentCount: 0,
    blockerCount: 0,
    overdue: false,
    archivedAt: "2026-08-08T09:00:00Z",
    labelIds: [],
    version: 3,
    createdAt: "2026-07-28T09:00:00Z",
    updatedAt: "2026-08-08T09:00:00Z",
  },
];
